### ISSUE TITLE
Remove initial folder selection

### ISSUE THREAD

**Issue by fungos** [crossuo/xuolauncher#14]
From a new install, right now launching the launcher will ask for a directory where to install CrossUO client.

Remove this step.

Assume a path by default, preferably somewhere in the following options depending on the OS/difficulty:
- User home or application data directory; or
- Side-by-side with the launcher; or
- Last option, inside the Launcher folder

**Comment by Nirad** [comment]
![capture d ecran 2019-01-30 a 20 09 43](https://user-images.githubusercontent.com/359353/52023416-0f969a80-24cb-11e9-8c39-3aeb53e91a1b.png)

**Comment by Nirad** [comment]
@fungos we can close?
