### ISSUE TITLE
Manager add latest

### ISSUE THREAD

**Issue by Nirad** [crossuo/xuolauncher#21]
Add latest to manager generating xml

**Comment by Nirad** [comment]
<release name="X:UO Launcher" version="1.0.0" latest="yes">
        <file name="XUOLauncher" hash="eb3455f380056b65" data="65/xuolauncher_eb3455f380056b65" datahash="2b01651c95399b33"/>
    </release>

**Comment by Nirad** [comment]
@fungos do we need incremental then ?

**Comment by fungos** [comment]
In this case not, as the download manager do already skip existing artifacts, the sum of all latest products will be equivalent to the incremental.
